### ISSUE TITLE
nieuwe klant

### ISSUE THREAD

**Issue by JanVanGoethem** [C4-Consulting-BVBA/C4.Orms.Issues#10]
bij het toevoegen van een klant krijg ik de melding dat ik niet al de nummers heb ingevuld maar het systeem duidt niet aan wat niet werd ingevuld. Ik vermoed de klantnummer maar deze zou automatisch voorgesteld moeten wordennieuw
![nieuwe klant](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/138875253/0cb50569-dcff-4941-abf6-d929e48381a6)

**Comment by carlhoogstoel** [comment]
Fixed in build 1.0.8681.19758 (08/10/2023 10:58:36)

![image](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/19626310/3e2d4bba-99cd-40b7-ae31-f79f7637ace9)
