### ISSUE TITLE
Adres opzoeken bij storingen

### ISSUE THREAD

**Issue by JanVanGoethem** [C4-Consulting-BVBA/C4.Orms.Issues#11]
systeem loopt vast
![adres opzoeken bij storingen](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/138875253/e8df3015-b1e9-461a-96c9-aabd39c2f8e3)
![adres opzoeken bij storingen](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/138875253/eb56701f-5bb8-433d-87a4-94fc4582df14)

**Comment by carlhoogstoel** [comment]
Fixed in build 1.0.8681.19758 (08/10/2023 10:58:36)

![image](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/19626310/dba73df3-9422-4588-87f0-d068c4291ce9)
