### ISSUE TITLE
Rondenummers wordt niet weergegeven bij contracten

### ISSUE THREAD

**Issue by JanVanGoethem** [C4-Consulting-BVBA/C4.Orms.Issues#14]
Bij het overzicht van de contracten wordt de naam van de technieker ingevuld ipv de rondenummer in de kolom Round
![Knipsel](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/138875253/f7b629c8-952d-4af4-8c77-b3b5c77be379)

**Comment by carlhoogstoel** [comment]
Fixed in build 1.0.8710.22303 (06/11/2023 12:23:26

![image](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/19626310/b044f0b6-65a5-4373-bc34-1ff38d354a11)
