### ISSUE TITLE
overzicht stockitems werkt niet

### ISSUE THREAD

**Issue by JanVanGoethem** [C4-Consulting-BVBA/C4.Orms.Issues#15]
overzicht stockitems werkt niet
![Knipsel](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/138875253/058ff537-76b1-4d29-90ab-d19bc9078f58)

**Comment by carlhoogstoel** [comment]
Fixed in build 1.0.8710.21557 (06/11/2023 11:58:34

![image](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/19626310/e0fbf990-b357-40f6-8b25-2bc1e5c4ad1d)
