### ISSUE TITLE
Geen zoekresultaat bij klanten bevat ora

### ISSUE THREAD

**Issue by JanVanGoethem** [C4-Consulting-BVBA/C4.Orms.Issues#4]
![geen zoekresultaat bij klanten](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/138875253/8047d637-cf0b-4981-b750-3665f379247d)

**Comment by carlhoogstoel** [comment]
Confirmed. Displayname is not correctly rendered.

![image](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/19626310/fdb4c02a-f82a-4390-bdba-019af9be0e12)

**Comment by carlhoogstoel** [comment]
Fixed as of build 1.0.8633

![image](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/19626310/e59e38de-b968-470e-b0e5-b0a70d7d7ab1)
