### ISSUE TITLE
Alle vakken worden niet ingevuld bij storingen

### ISSUE THREAD

**Issue by JanVanGoethem** [C4-Consulting-BVBA/C4.Orms.Issues#6]
![image](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/19626310/5f19bd88-85a3-4210-996e-577a47bd8883)

**Comment by carlhoogstoel** [comment]
Fixed in build 1.0.8654.39641 (11/09/2023 22:01:22)

![image](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/19626310/39bd397b-d270-41be-b647-1811d93e7e6f)
