### ISSUE TITLE
Postcode selecteren bij nieuw contract

### ISSUE THREAD

**Issue by JanVanGoethem** [C4-Consulting-BVBA/C4.Orms.Issues#9]
als je een postcode ingeeft bij een nieuw contract krijg je een dropdown maar je kan de gewenste gemeente niet selecteren.

**Comment by carlhoogstoel** [comment]
Fixed in build 1.0.8681.19758 (08/10/2023 10:58:36)

![image](https://github.com/C4-Consulting-BVBA/C4.Orms.Issues/assets/19626310/8656cf31-55e7-4543-ba48-7efd8f1ea0db)
